name: ARM64 CI

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'

jobs:
  build-and-test-arm:
    name: ${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm64]
        compiler: [gcc, clang]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Set up compiler
      run: |
        if [ "${{ matrix.compiler }}" == "gcc" ]; then
          # Add GCC 14 PPA and install
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
          echo "CC=gcc-14" >> $GITHUB_ENV
          echo "CXX=g++-14" >> $GITHUB_ENV
        elif [ "${{ matrix.compiler }}" == "clang" ]; then
          # Add LLVM 18 repository and install
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" -y
          sudo apt-get update
          sudo apt-get install -y clang-18 clang++-18
          echo "CC=clang-18" >> $GITHUB_ENV
          echo "CXX=clang++-18" >> $GITHUB_ENV
        fi

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: |
        cmake .. \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build
      working-directory: build
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Run tests
      working-directory: build
      run: ctest --output-on-failure --build-config ${{ matrix.build_type }}

    - name: Upload build artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}
        path: |
          build/CMakeFiles/CMakeOutput.log
          build/CMakeFiles/CMakeError.log
          build/compile_commands.json